### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by titu3e** [kaif-00z/AutoAnimeBot#15]
![image](https://github.com/user-attachments/assets/0936f684-5c5d-4c6b-b3a6-5e0da17bafbc)

```
09/09/2024, 06:06:00 || AutoAnimeBot [INFO] : Successfully Connected to Firebase Database
09/09/2024, 06:06:01 || AutoAnimeBot [INFO] : Succesfully Sync Database!!!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 900, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'corn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/bot.py", line 40, in <module>
    schedule = ScheduleTasks(bot)
  File "/usr/src/app/functions/schedule.py", line 43, in __init__
    self.sch.add_job(self.restart, "corn", hour=2, minute=1)  # 2:01 AM IST
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 424, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 925, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 908, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "corn" was found
```

**Comment by kaif-00z** [comment]
Thanks For Raising The Issue.

https://github.com/kaif-00z/AutoAnimeBot/commit/962959535486ad259dbf83c845ceb7a3695a1d9c

Fixed Now!!
