### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by rizz-electrical-engg** [kaif-00z/AutoAnimeBot#16]
Traceback (most recent call last):
  File "/root/AutoAnimeBot/bot.py", line 35, in <module>
    tools.init_dir()
  File "/root/AutoAnimeBot/functions/tools.py", line 135, in init_dir
    content = requests.get(Var.THUMB).content
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

**Comment by kaif-00z** [comment]
ig u added invalid link on THUMBNAIL var

**Comment by rizz-electrical-engg** [comment]
actually i did not put any THUMBNAIL VAR cause its OPTIONAL

**Comment by rizz-electrical-engg** [comment]
Solved I put my thumb var .
