### ISSUE TITLE
Another Error 🤧

### ISSUE THREAD

**Issue by rizz-electrical-engg** [kaif-00z/AutoAnimeBot#17]
10/05/2024, 16:37:54 || AutoAnimeBot [ERROR] : [
10/05/2024, 16:38:18 || AutoAnimeBot [ERROR] : [
10/05/2024, 16:39:01 || AutoAnimeBot [ERROR] : [
10/05/2024, 16:39:15 || Telethon.client.uploads [INFO] : Uploading file of 771809 bytes in 6 chunks of 131072
 10/05/2024, 16:40:05 || AutoAnimeBot [ERROR] : [
10/05/2024, 16:41:58 || Telethon.client.uploads [INFO] : Uploading file of 4359
bytes in 1 chunks of 131072
10/05/2024, 16:41:58 || Telethon.client.uploads [INFO] : Uploading file of 40622 bytes in 1 chunks of 131072
10/05/2024, 16:42:54 || AutoAnimeBot [ERROR] : [

**Comment by kaif-00z** [comment]
check telegram log channel and send me that error

**Comment by rizz-electrical-engg** [comment]
Showing peer id is invalid but I added bot in it and also tagged it too .





[ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002322801528'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/core/executors.py", line 78, in execute
    msg = await self.bot.upload_anime(
  File "/usr/src/app/core/bot.py", line 120, in upload_anime
    post = await self.pyro_client.send_document(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/send_document.py", line 195, in send_document
    peer=await self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 89, in resolve_peer
    peer_type = utils.get_peer_type(peer_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/utils.py", line 246, in get_peer_type
    raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: -1002322801528

**Comment by kaif-00z** [comment]
ig u haven't promoted bot to admin, use gen_env script to avoid this type of errors

**Comment by rizz-electrical-engg** [comment]
Ok

**Comment by rizz-electrical-engg** [comment]
All encods going failed ??

**Comment by kaif-00z** [comment]
> All encods going failed ??

ig coz of low powered cpu

**Comment by rizz-electrical-engg** [comment]
Nahh bro I got 6 core with 16gb Ram Ig that's enough for that

**Comment by kaif-00z** [comment]
pushing a optimization fix today wait

**Comment by kaif-00z** [comment]
> Nahh bro I got 6 core with 16gb Ram Ig that's enough for that

or ig u haven't installed ffmpeg and following tools

**Comment by rizz-electrical-engg** [comment]
I downloaded all bro I'm running another encode bot too and it's working

**Comment by kaif-00z** [comment]
https://github.com/kaif-00z/AutoAnimeBot/commit/39c50b1ecf7fe67c0da339052cb3bb582087c353
