### ISSUE TITLE
Executor & Tool Error

### ISSUE THREAD

**Issue by DARKY-LAB** [kaif-00z/AutoAnimeBot#18]
[ERROR] Traceback (most recent call last):
  File "C:\Users\lotus\Downloads\Compressed\Working\AutoAnimeBot-main\AutoAnimeBot-main\core\executors.py", line 70, in execute
    succ, _new_msg = await self.tools.compress(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.input_file, self.output_file, _log_msg
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\lotus\Downloads\Compressed\Working\AutoAnimeBot-main\AutoAnimeBot-main\functions\tools.py", line 204, in compress
    total_frames = await self.frame_counts(dl)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lotus\Downloads\Compressed\Working\AutoAnimeBot-main\AutoAnimeBot-main\functions\tools.py", line 201, in frame_counts
    return _x.split(":")[1].split("\n")[0]
           ~~~~~~~~~~~~~^^^
IndexError: list index out of range




[AutoAnimeBot.log](https://github.com/user-attachments/files/17610085/AutoAnimeBot.log)

**Comment by kaif-00z** [comment]
As I Can See Here, You Are Trying To Deploy In Windows Platform and the fact is we don't recommend Windows for this project + if you are in windows try to deploy repo using docker.

This repo is made for linux based vps

**Comment by DARKY-LAB** [comment]
let me try using it on docker

**Comment by DARKY-LAB** [comment]
[ERROR] Traceback (most recent call last):
  File "/media/darkxside78/Local Disk/Compressed/Working/AutoAnimeBot-main/AutoAnimeBot-main/functions/tools.py", line 154, in rename_file
    os.rename(dl, out)
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/[SubsPlease] Tasuuketsu - 17 (480p) [3B7A901A].mkv' -> 'encode/[S1-17] TASUKETSU -Fate of the Majority- [480p].mkv'


Bro it's showing this
